package dev.GraphVisualizer.ui.canvas;

import dev.GraphVisualizer.models.Edge;
import dev.GraphVisualizer.models.Graph;
import dev.GraphVisualizer.models.Node;
import dev.GraphVisualizer.service.AlgorithmAddInfo;
import dev.GraphVisualizer.service.CommandManager;
import dev.GraphVisualizer.service.GraphService;

import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.Group;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.TextInputDialog;
import javafx.scene.layout.HBox;
import javafx.scene.layout.Pane;
import javafx.scene.layout.VBox;
import javafx.scene.paint.Color;
import javafx.scene.shape.Circle;
import javafx.scene.shape.Line;
import javafx.scene.shape.Polygon;
import javafx.scene.shape.Rectangle;
import javafx.scene.text.Font;
import javafx.scene.text.FontWeight;
import javafx.scene.text.Text;
import javafx.beans.binding.Bindings;
import javafx.scene.input.MouseButton;
import javafx.scene.input.MouseEvent;
import javafx.scene.transform.Affine;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;

/** Class GraphCanvas - interactive area responsible for drawing and editing the graph */
public class GraphCanvas extends Pane {
    /** Group containing all zoomed and panned graph visuals */
    private final Group graphGroup = new Group();
    /** Panning gesture origin and current translation */
    private double dragStartX, dragStartY, translateX, translateY;
    /** Flag marking that the viewport is currently being panned */
    private boolean isPanning = false;

    /** Container with zoom buttons */
    private final VBox zoomControls = new VBox(4);
    /** Legend shown when algorithm state is displayed */
    private final VBox legend = new VBox(5);
    /** Current zoom scale */
    private double scale = 1.0;
    private static final double SCALE_STEP = 0.2;
    private static final double SCALE_MIN  = 0.2;
    private static final double SCALE_MAX  = 3.0;
    private static final double NODE_RADIUS = 22.0;

    /** Graph service used as the canvas data source */
    private final GraphService graphService;
    /** Shared undo/redo manager */
    private final CommandManager commandManager;
    /** Current interaction mode */
    private CanvasMode mode = CanvasMode.PAN;
    /** Node selected as the start of a new edge */
    private Node selectedNode = null;
    /** Counter used for autogenerated node labels */
    private int  nodeCounter  = 0;
    /** Whether the current graph is directed */
    private boolean directed;
    /** Whether the current graph is weighted */
    private boolean weighted;
    /** Node currently being dragged in pan mode */
    private Node draggingNode = null;
    /** Original x position before dragging started */
    private double dragNodeOrigX = 0;
    /** Original y position before dragging started */
    private double dragNodeOrigY = 0;
    /** Flag marking that a node drag gesture is active */
    private boolean isDraggingNode = false;
    /** Prevents drag-release from being interpreted as a click */
    private boolean nodeDragConsumed  = false;

    /** Highlighted path reconstructed after Dijkstra */
    private List<Node> highlightedPath = new ArrayList<>();
    /** Color used to highlight nodes and edges belonging to a path */
    private static final Color PATH_COLOR = Color.web("#fde047");

    /** Shared transform used for zooming and panning */
    private final Affine viewTransform = new Affine();

    /** Reverse lookup from rendered node circles to model nodes */
    private final Map<Circle, Node> circleToNode = new HashMap<>();
    /** Reverse lookup from rendered edge lines to model edges */
    private final Map<Line, Edge> lineToEdge = new HashMap<>();

    /** Algorithm state overlay, null when no algorithm has been run */
    private Map<Node, AlgorithmAddInfo> algorithmState = null;

    private Color NODE_FILL = Color.web("#0ea5e9");
    private Color NODE_STROKE = Color.web("#38bdf8");
    private Color NODE_SELECTED = Color.web("#f59e0b");
    private Color EDGE_COLOR = Color.web("#475569");
    private Color NODE_LABEL_COLOR = Color.web("#f1f5f9");
    private Color EDGE_WEIGHT_COLOR = Color.web("#7dd3fc");
    private Color ALGO_WHITE = Color.web("#334155");   // unvisited during algorithm
    private Color ALGO_GREY = Color.web("#f59e0b");    // in-queue / being processed
    private Color ALGO_BLACK = Color.web("#4ade80");   // finished

    private boolean darkTheme = true;


    /** Available canvas interaction modes */
    public enum CanvasMode {
        /** Moves the viewport without changing the graph. */
        PAN,
        /** Adds a node at the selected canvas position. */
        ADD_NODE,
        /** Adds an edge between selected nodes. */
        ADD_EDGE,
        /** Removes the selected node or edge. */
        REMOVE
    }

    /**
     * Constructor taking services and graph flags required by the canvas.
     * @param graphService graph service used by the canvas
     * @param directed whether the graph is directed
     * @param weighted whether the graph is weighted
     * @param commandManager shared undo/redo manager
     */
    public GraphCanvas(GraphService graphService, boolean directed, boolean weighted, CommandManager commandManager) {
        this.graphService = graphService;
        this.directed = directed;
        this.weighted = weighted;
        this.commandManager = commandManager;
        this.nodeCounter = graphService.getGraph().getAllNodes().size();

        applyTheme();

        clipProperty().bind(Bindings.createObjectBinding(
            () -> new Rectangle(getWidth(), getHeight()), widthProperty(), heightProperty()));

        graphGroup.getTransforms().add(viewTransform);

        zoomControls.setAlignment(Pos.CENTER);
        zoomControls.setPadding(new Insets(4));

        Button zoomIn  = makeZoomBtn("+");
        Button zoomOut = makeZoomBtn("-");
        zoomIn.setOnAction(e -> applyZoom(SCALE_STEP));
        zoomOut.setOnAction(e -> applyZoom(-SCALE_STEP));
        zoomControls.getChildren().addAll(zoomIn, zoomOut);
        zoomControls.layoutXProperty().bind(widthProperty().subtract(zoomControls.widthProperty()).subtract(12));
        zoomControls.setLayoutY(12);

        legend.setLayoutX(12);
        legend.layoutYProperty().bind(heightProperty().subtract(legend.heightProperty()).subtract(12));
        legend.setVisible(false);
        buildLegend();

        getChildren().addAll(graphGroup, zoomControls, legend);
        addPanHandlers();
        addCanvasClickHandler();
        refresh();
    }

    /**
     * Creates a styled zoom control button.
     * @param text button label
     * @return configured zoom button
     */
    private Button makeZoomBtn(String text) {
        Button b = new Button(text);
        b.setMinSize(32, 32);
        b.setStyle(
            "-fx-background-color: #3d3d5c; -fx-text-fill: #f3f4f6; " +
            "-fx-font-size: 16; -fx-cursor: hand; -fx-border-radius: 6; -fx-background-radius: 6;");
        return b;
    }

    /**
     * Enables the dark or light theme and redraws the canvas.
     * @param dark true for dark theme, false for light theme
     */
    public void setDarkTheme(boolean dark) {
        this.darkTheme = dark;
        applyTheme();
        refresh();
    }

    /** Applies the currently selected theme colors to the canvas UI. */
    private void applyTheme() {
        if (darkTheme) {
            setStyle("-fx-background-color: #0f172a;");
            zoomControls.setStyle("-fx-background-color: #1e293b; -fx-background-radius: 8; -fx-border-radius: 8;");
            NODE_FILL = Color.web("#0ea5e9");
            NODE_STROKE = Color.web("#38bdf8");
            EDGE_COLOR = Color.web("#475569");
            NODE_LABEL_COLOR = Color.web("#f1f5f9");
            EDGE_WEIGHT_COLOR = Color.web("#7dd3fc");
            ALGO_WHITE = Color.web("#334155");
            ALGO_GREY = Color.web("#f59e0b");
            ALGO_BLACK = Color.web("#4ade80");
        } else {
            setStyle("-fx-background-color: #f1f5f9;");
            zoomControls.setStyle("-fx-background-color: #cbd5e1; -fx-background-radius: 8; -fx-border-radius: 8;");
            NODE_FILL = Color.web("#3b82f6");
            NODE_STROKE = Color.web("#1d4ed8");
            EDGE_COLOR = Color.web("#64748b");
            NODE_LABEL_COLOR = Color.web("#0f172a");
            EDGE_WEIGHT_COLOR = Color.web("#1e40af");
            ALGO_WHITE = Color.web("#94a3b8");
            ALGO_GREY = Color.web("#f97316");
            ALGO_BLACK = Color.web("#15803d");
        }
        NODE_SELECTED = Color.web("#e11d48");
        if (legend.isVisible())
            buildLegend();
    }

    /**
     * Changes the current interaction mode.
     * @param mode new canvas mode
     */
    public void setMode(CanvasMode mode) {
        this.mode = mode;
        this.selectedNode = null;
        refresh();
    }

    /**
     * Updates graph type flags used when rendering edges and weights.
     * @param directed true when the graph is directed
     * @param weighted true when the graph is weighted
     */
    public void updateGraphType(boolean directed, boolean weighted) {
        this.directed = directed;
        this.weighted = weighted;
        refresh();
    }

    /**
     * Overlays algorithm result colors and distance labels on the canvas.
     * @param state algorithm state to display for each node
     */
    public void showAlgorithmResult(Map<Node, AlgorithmAddInfo> state) {
        this.algorithmState = state;
        this.highlightedPath = new ArrayList<>();
        buildLegend();
        legend.setVisible(true);
        refresh();
    }

    /** Removes algorithm result overlay and restores normal node colors. */
    public void clearAlgorithmResult() {
        this.algorithmState = null;
        legend.setVisible(false);
        clearPath();
    }

    /**
     * Highlights the provided path on the canvas.
     * @param path ordered path to highlight
     */
    public void showPath(List<Node> path) {
        this.highlightedPath = path;
        refresh();
    }

    /** Clears any highlighted path from the canvas. */
    public void clearPath() {
        this.highlightedPath = new ArrayList<>();
        refresh();
    }

    /** Resets the autogenerated node label counter. */
    public void resetNodeCounter() {
        nodeCounter = 0;
    }

    /** Synchronizes the node label counter with the current graph size. */
    public void syncNodeCounterWithGraph() {
        nodeCounter = graphService.getGraph().getAllNodes().size();
    }

    /** Resets zoom and panning to the default viewport. */
    public void resetViewport() {
        scale = 1.0;
        translateX = 0.0;
        translateY = 0.0;
        viewTransform.setToIdentity();
    }

    /** Redraws the whole graph view from the current model state. */
    public void refresh() {
        graphGroup.getChildren().clear();
        circleToNode.clear();
        lineToEdge.clear();
        drawEdges();
        drawNodes();
    }

    /** Draws all nodes together with labels and algorithm overlays. */
    private void drawNodes() {
        for (Node node : graphService.getGraph().getAllNodes()) {
            Color fill;
            if (algorithmState != null && algorithmState.containsKey(node)) {
                fill = switch (algorithmState.get(node).getNodeColor()) {
                    case WHITE -> ALGO_WHITE;
                    case GREY  -> ALGO_GREY;
                    case BLACK -> ALGO_BLACK;
                };
            } else {
                fill = (node == selectedNode) ? NODE_SELECTED : NODE_FILL;
            }

            Circle circle = new Circle(node.getPositionX(), node.getPositionY(), NODE_RADIUS, fill);
            boolean nodeOnPath = highlightedPath.contains(node);
            circle.setStroke(nodeOnPath ? PATH_COLOR : (node == selectedNode) ? NODE_SELECTED : NODE_STROKE);
            circle.setStrokeWidth(nodeOnPath ? 4 : 2);

            Text label = new Text(node.getLabel());
            label.setFill(NODE_LABEL_COLOR);
            label.setFont(Font.font("System", FontWeight.BOLD, 13));
            label.setX(node.getPositionX() - label.getLayoutBounds().getWidth() / 2);
            label.setY(node.getPositionY() + label.getLayoutBounds().getHeight() / 4);
            label.setMouseTransparent(true);

            circle.setOnMouseClicked(e -> {
                if (e.getButton() == MouseButton.SECONDARY) {
                    handleNodeDoubleClick(node);
                    e.consume();
                    return;
                }
                if (e.getClickCount() == 2) {
                    handleNodeDoubleClick(node);
                } else {
                    handleNodeClick(node, e);
                }
                e.consume();
            });

            circleToNode.put(circle, node);
            graphGroup.getChildren().addAll(circle, label);

            // distance label below node when an algorithm has run
            if (algorithmState != null && algorithmState.containsKey(node)) {
                double d = algorithmState.get(node).getD();
                if (d != Double.POSITIVE_INFINITY) {
                    String dStr = (d == Math.floor(d))
                        ? String.valueOf((long) d)
                        : String.format("%.1f", d);
                    Text dist = new Text(dStr);
                    dist.setFill(NODE_LABEL_COLOR);
                    dist.setFont(Font.font("System", FontWeight.BOLD, 16));
                    dist.setX(node.getPositionX() - dist.getLayoutBounds().getWidth() / 2);
                    dist.setY(node.getPositionY() - NODE_RADIUS - 6);
                    dist.setMouseTransparent(true);
                    graphGroup.getChildren().add(dist);
                }
            }
        }
    }

    /** Draws all edges, arrows, weights and invisible hit areas. */
    private void drawEdges() {
        for (Edge edge : graphService.getGraph().getAllEdges()) {
            Node src = edge.getSource();
            Node tgt = edge.getTarget();
            if (src == null || tgt == null)
                continue;
            boolean onPath = false;
            for (int i = 0; i < highlightedPath.size() - 1; i++) {
                Node p = highlightedPath.get(i);
                Node q = highlightedPath.get(i + 1);
                if ((src.equals(p) && tgt.equals(q)) || (src.equals(q) && tgt.equals(p))) {
                    onPath = true; break;
                }
            }
            Color lineColor = onPath ? PATH_COLOR : EDGE_COLOR;
            Line line = new Line(src.getPositionX(), src.getPositionY(), tgt.getPositionX(), tgt.getPositionY());
            line.setStroke(lineColor);
            line.setStrokeWidth(onPath ? 5 : 3);
            lineToEdge.put(line, edge);
            graphGroup.getChildren().add(line);

            if (directed) {
                Polygon arrow = buildArrow(src, tgt);
                arrow.setFill(lineColor);
                graphGroup.getChildren().add(arrow);
            }

            if (weighted) {
                double mx = (src.getPositionX() + tgt.getPositionX()) / 2;
                double my = (src.getPositionY() + tgt.getPositionY()) / 2;
                double edgeDx = tgt.getPositionX() - src.getPositionX();
                double edgeDy = tgt.getPositionY() - src.getPositionY();
                double edgeLen = Math.sqrt(edgeDx * edgeDx + edgeDy * edgeDy);
                double perpX = edgeLen == 0 ? 0 : -edgeDy / edgeLen * 14;
                double perpY = edgeLen == 0 ? 0 : edgeDx / edgeLen * 14;
                Text wLabel = new Text(String.format("%.1f", edge.getWeight()));
                wLabel.setFill(EDGE_WEIGHT_COLOR);
                wLabel.setFont(Font.font("System", FontWeight.BOLD, 13));
                wLabel.setX(mx + perpX - wLabel.getLayoutBounds().getWidth() / 2);
                wLabel.setY(my + perpY + wLabel.getLayoutBounds().getHeight() / 4);
                graphGroup.getChildren().add(wLabel);
            }

            // Wide transparent line on top so edges are easy to click
            Line hitLine = new Line(src.getPositionX(), src.getPositionY(), tgt.getPositionX(), tgt.getPositionY());
            hitLine.setStroke(Color.TRANSPARENT);
            hitLine.setStrokeWidth(14);
            hitLine.setOnMouseClicked(e -> {
                if (e.getButton() == MouseButton.SECONDARY) {
                    handleEdgeDoubleClick(edge);
                    e.consume();
                    return;
                }
                if (e.getClickCount() == 2) {
                    handleEdgeDoubleClick(edge);
                }
                else {
                    handleEdgeClick(edge, e);
                }
                e.consume();
            });
            graphGroup.getChildren().add(hitLine);
        }
    }

    /**
     * Builds an arrow head polygon for a directed edge.
     * @param src source node
     * @param tgt target node
     * @return polygon representing the arrow head
     */
    private Polygon buildArrow(Node src, Node tgt) {
        double dx = tgt.getPositionX() - src.getPositionX();
        double dy = tgt.getPositionY() - src.getPositionY();
        double len = Math.sqrt(dx * dx + dy * dy);
        if (len == 0) {
            return new Polygon();
        }

        double ux = dx / len;
        double uy = dy / len;

        double tipX = tgt.getPositionX() - ux * NODE_RADIUS;
        double tipY = tgt.getPositionY() - uy * NODE_RADIUS;

        double arrowLen  = 14;
        double arrowHalf = 6;
        double baseX = tipX - ux * arrowLen;
        double baseY = tipY - uy * arrowLen;
        double perpX = -uy * arrowHalf;
        double perpY =  ux * arrowHalf;

        return new Polygon(
            tipX, tipY,
            baseX + perpX, baseY + perpY,
            baseX - perpX, baseY - perpY
        );
    }

    /**
     * Converts screen x coordinate into graph-space x coordinate.
     * @param screenX x coordinate in screen space
     * @return x coordinate in graph space
     */
    private double screenToGraphX(double screenX) {
        return (screenX - translateX) / scale;
    }

    /**
     * Converts screen y coordinate into graph-space y coordinate.
     * @param screenY y coordinate in screen space
     * @return y coordinate in graph space
     */
    private double screenToGraphY(double screenY) {
        return (screenY - translateY) / scale;
    }

    /** Registers clicks on empty canvas space for node creation. */
    private void addCanvasClickHandler() {
        addEventFilter(MouseEvent.MOUSE_CLICKED, e -> {
            if (nodeDragConsumed) {
                nodeDragConsumed = false;
                e.consume();
                return;
            }
            if (zoomControls.getBoundsInParent().contains(e.getX(), e.getY())) {
                return;
            }
            if (legend.isVisible() && legend.getBoundsInParent().contains(e.getX(), e.getY())) {
                return;
            }
            if (mode == CanvasMode.ADD_NODE) {
                double graphX = screenToGraphX(e.getX());
                double graphY = screenToGraphY(e.getY());
                if (!isOverNode(graphX, graphY)) {
                    addNode(graphX, graphY);
                }
            }
        });
    }

    /**
     * Handles a click on a node according to the active canvas mode.
     * @param node clicked node
     * @param e original mouse event
     */
    private void handleNodeClick(Node node, MouseEvent e) {
        switch (mode) {
            case ADD_EDGE -> {
                if (selectedNode == null) {
                    selectedNode = node;
                    refresh();
                } else if (selectedNode != node) {
                    double w = 1.0;
                    if (weighted) {
                        TextInputDialog wd = new TextInputDialog("1.0");
                        wd.setTitle("Edge weight");
                        String sep = directed ? " → " : " — ";
                        wd.setHeaderText(selectedNode.getLabel() + sep + node.getLabel());
                        wd.setContentText("Weight:");
                        wd.initOwner(getScene().getWindow());
                        styleDialog(wd);
                        Optional<String> wr = wd.showAndWait();
                        if (wr.isEmpty()) { selectedNode = null; refresh(); return; }
                        try { w = Double.parseDouble(wr.get()); }
                        catch (NumberFormatException ignored) { selectedNode = null; refresh(); return; }
                    }
                    double finalW = w;
                    Node src = selectedNode;
                    Edge newEdge = new Edge(src, node, finalW);
                    Graph graph = graphService.getGraph();
                    commandManager.push(
                        () -> graph.addEdge(newEdge),
                        () -> graph.removeEdge(newEdge)
                    );
                    selectedNode = null;
                    refresh();
                }
            }
            case REMOVE -> {
                Graph graph = graphService.getGraph();
                List<Edge> removed = graph.getAllEdges().stream()
                    .filter(ed -> ed.getSource() == node || ed.getTarget() == node)
                    .toList();
                commandManager.push(
                    () -> { removed.forEach(graph::removeEdge); graph.removeNode(node); },
                    () -> { graph.addNode(node); removed.forEach(graph::addEdge); }
                );
                refresh();
            }
            default -> {}
        }
    }

    /**
     * Handles a click on an edge according to the active canvas mode.
     * @param edge clicked edge
     * @param e original mouse event
     */
    private void handleEdgeClick(Edge edge, MouseEvent e) {
        if (mode == CanvasMode.REMOVE) {
            Graph graph = graphService.getGraph();
            commandManager.push(
                () -> graph.removeEdge(edge),
                () -> graph.addEdge(edge)
            );
            refresh();
        }
    }

    /**
     * Opens a rename dialog for the given node.
     * @param node node to rename
     */
    private void handleNodeDoubleClick(Node node) {
        TextInputDialog dialog = new TextInputDialog(node.getLabel());
        dialog.setTitle("Rename node");
        dialog.setHeaderText(null);
        dialog.setContentText("New label:");
        dialog.initOwner(getScene().getWindow());
        styleDialog(dialog);
        Optional<String> result = dialog.showAndWait();
        result.filter(s -> !s.isBlank()).ifPresent(s -> {
            String oldLabel = node.getLabel();
            commandManager.push(
                () -> node.setLabel(s),
                () -> node.setLabel(oldLabel)
            );
            refresh();
        });
    }

    /**
     * Opens a weight edit dialog for the given edge.
     * @param edge edge whose weight should be edited
     */
    private void handleEdgeDoubleClick(Edge edge) {
        if (!weighted) {
            return;
        }
        TextInputDialog dialog = new TextInputDialog(String.valueOf(edge.getWeight()));
        dialog.setTitle("Edit weight");
        String sep = directed ? " → " : " — ";
        dialog.setHeaderText(edge.getSource().getLabel() + sep + edge.getTarget().getLabel());
        dialog.setContentText("Weight:");
        dialog.initOwner(getScene().getWindow());
        styleDialog(dialog);
        Optional<String> result = dialog.showAndWait();
        result.ifPresent(s -> {
            try {
                double newWeight = Double.parseDouble(s);
                double oldWeight = edge.getWeight();
                commandManager.push(
                    () -> edge.setWeight(newWeight),
                    () -> edge.setWeight(oldWeight)
                );
                refresh();
            } catch (NumberFormatException ignored) {}
        });
    }

    /** Rebuilds the algorithm-state legend. */
    private void buildLegend() {
        legend.getChildren().clear();
        String bg = darkTheme ? "#1e293b" : "#e2e8f0";
        String fg = darkTheme ? "#cbd5e1" : "#334155";
        legend.setStyle(
            "-fx-background-color: " + bg + "; -fx-background-radius: 8; " +
            "-fx-border-radius: 8; -fx-padding: 8 12;");
        Label title = new Label("Algorithm colors (CLRS):");
        title.setStyle("-fx-text-fill: " + fg + "; -fx-font-weight: bold; -fx-font-size: 12;");
        legend.getChildren().addAll(
            title,
            legendItem(ALGO_WHITE, "WHITE — unvisited", fg),
            legendItem(ALGO_GREY,  "GREY  — in queue / processing", fg),
            legendItem(ALGO_BLACK, "BLACK — finished", fg)
        );
    }

    /**
     * Creates a single legend row.
     * @param color color sample shown in the row
     * @param text legend label
     * @param fg foreground text color
     * @return configured legend row
     */
    private HBox legendItem(Color color, String text, String fg) {
        Circle dot = new Circle(7, color);
        dot.setStroke(color.darker());
        dot.setStrokeWidth(1);
        Label lbl = new Label(text);
        lbl.setStyle("-fx-text-fill: " + fg + "; -fx-font-size: 11; -fx-font-family: monospace;");
        HBox row = new HBox(8, dot, lbl);
        row.setAlignment(Pos.CENTER_LEFT);
        return row;
    }

    /**
     * Applies consistent styling to text-input dialogs opened from the canvas.
     * @param dialog dialog to style
     */
    private void styleDialog(TextInputDialog dialog) {
        dialog.getDialogPane().setStyle(
            "-fx-background-color: #2d2d3f; -fx-font-size: 13px;");
        javafx.scene.Node content = dialog.getDialogPane().lookup(".content.label");
        if (content != null) {
            content.setStyle("-fx-text-fill: #f3f4f6;");
        }
    }

    /**
     * Adds a new node at the given graph-space position.
     * @param x x coordinate in graph space
     * @param y y coordinate in graph space
     */
    private void addNode(double x, double y) {
        Node node = new Node(generateLabel(), x, y);
        Graph graph = graphService.getGraph();
        commandManager.push(
            () -> graph.addNode(node),
            () -> graph.removeNode(node)
        );
        refresh();
    }

    /**
     * Generates the next sequential node label.
     * @return next autogenerated label
     */
    private String generateLabel() {
        int n = nodeCounter++;
        StringBuilder sb = new StringBuilder();
        do {
            sb.insert(0, (char) ('A' + n % 26));
            n = n / 26 - 1;
        } while (n >= 0);
        return sb.toString();
    }

    /**
     * Checks whether the given graph-space point overlaps an existing node.
     * @param x x coordinate in graph space
     * @param y y coordinate in graph space
     * @return true when a node occupies the position
     */
    private boolean isOverNode(double x, double y) {
        return getNodeAt(x, y) != null;
    }

    /**
     * Finds the node located at the given graph-space position.
     * @param x x coordinate in graph space
     * @param y y coordinate in graph space
     * @return node under the point or null when there is none
     */
    private Node getNodeAt(double x, double y) {
        for (Node node : graphService.getGraph().getAllNodes()) {
            double dx = node.getPositionX() - x;
            double dy = node.getPositionY() - y;
            if (Math.sqrt(dx * dx + dy * dy) < NODE_RADIUS) return node;
        }
        return null;
    }

    /**
     * Applies zoom while keeping the viewport center stable.
     * @param delta zoom increment
     */
    private void applyZoom(double delta) {
        double oldScale = scale;
        scale = Math.max(SCALE_MIN, Math.min(SCALE_MAX, scale + delta));
        if (scale == oldScale) return;
        // zoom towards the centre of the visible viewport
        double cx = getWidth() / 2.0;
        double cy = getHeight() / 2.0;
        translateX = cx - (cx - translateX) * scale / oldScale;
        translateY = cy - (cy - translateY) * scale / oldScale;
        viewTransform.setMxx(scale);
        viewTransform.setMyy(scale);
        viewTransform.setTx(translateX);
        viewTransform.setTy(translateY);
    }

    /** Registers panning and node-dragging mouse handlers. */
    private void addPanHandlers() {
        addEventFilter(MouseEvent.MOUSE_PRESSED, e -> {
            if (zoomControls.getBoundsInParent().contains(e.getX(), e.getY())) {
                isPanning = false;
                return;
            }
            double gx  = screenToGraphX(e.getX());
            double gy  = screenToGraphY(e.getY());
            Node hit = getNodeAt(gx, gy);
            if (mode == CanvasMode.PAN && hit != null && e.getButton() == MouseButton.PRIMARY) {
                draggingNode  = hit;
                dragNodeOrigX = hit.getPositionX();
                dragNodeOrigY = hit.getPositionY();
                isDraggingNode = true;
                isPanning      = false;
            } else if (mode == CanvasMode.PAN && e.getButton() == MouseButton.PRIMARY) {
                isPanning  = true;
                dragStartX = e.getX() - translateX;
                dragStartY = e.getY() - translateY;
            }
            e.consume();
        });

        addEventFilter(MouseEvent.MOUSE_DRAGGED, e -> {
            if (mode == CanvasMode.PAN && isDraggingNode && draggingNode != null) {
                draggingNode.setPositionX(screenToGraphX(e.getX()));
                draggingNode.setPositionY(screenToGraphY(e.getY()));
                graphService.getGraph().setCache(true);
                refresh();
                e.consume();
            } else if (isPanning) {
                translateX = e.getX() - dragStartX;
                translateY = e.getY() - dragStartY;
                viewTransform.setTx(translateX);
                viewTransform.setTy(translateY);
                e.consume();
            }
        });

        addEventFilter(MouseEvent.MOUSE_RELEASED, e -> {
            if (mode == CanvasMode.PAN && isDraggingNode && draggingNode != null) {
                Node node = draggingNode;
                double newX = node.getPositionX();
                double newY = node.getPositionY();
                double origX = dragNodeOrigX;
                double origY = dragNodeOrigY;
                if (newX != origX || newY != origY) {
                    nodeDragConsumed = true;
                    commandManager.push(
                        () -> { node.setPositionX(newX);  node.setPositionY(newY);  refresh(); },
                        () -> { node.setPositionX(origX); node.setPositionY(origY); refresh(); }
                    );
                }
            }
            isDraggingNode = false;
            draggingNode = null;
            isPanning = false;
        });
    }
}
